#!/bin/bash
source $OPENSHIFT_CARTRIDGE_SDK_BASH

if [ -z "$(ps -ef | grep gunicorn | grep -v grep)" ]
then
    client_result "Gunicorn is already stopped"
else
    kill `ps -ef | grep gunicorn | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
fi

if [ -z "$(ps -ef | grep 'python3.5' | grep -v grep)" ]
then
    client_result "Python is already stopped"
else
    kill `ps -ef | grep 'python3.5' | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
fi
